import React, {useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import {budgetHistory} from './budgetHistory';
import Simulation from './Simulation';
const formatMoney=(v,currency='MXN')=>v===null||v===undefined?'Pendiente':new Intl.NumberFormat('es-MX',{style:'currency',currency,maximumFractionDigits:2}).format(v);
async function api(path, options){const r=await fetch('/api'+path,{...options,credentials:'include',headers:{...(!(options?.body instanceof FormData)?{'Content-Type':'application/json'}:{}),'X-App':'1',...options?.headers}});const data=await r.json();if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:Array.isArray(data.detail)?data.detail.map(x=>`${({username:'Usuario',password:'Contraseña',role:'Rol'})[x.loc?.at(-1)]||x.loc?.at(-1)||'Campo'}: ${x.msg}`).join('. '):'No se pudo completar la solicitud');return data;}
const descriptions={'Resumen':'Consulta ingresos, egresos, resultados pendientes y desviaciones del periodo.','Presupuestos':'Revisa cada partida por categoría, concepto y periodo del archivo importado.','Simulación':'Explora cómo cambiaría el gasto real del mes al ajustar nómina, otros egresos y precios.','Importaciones':'Carga archivos CSV para incorporar y validar el histórico financiero.','Power BI':'Consulta el estado de la integración de reportes corporativos con Power BI.','Usuarios':'Crea cuentas, asigna roles y consulta los usuarios registrados.'};
const monthLabel=p=>p?new Intl.DateTimeFormat('es-MX',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${p}-01T00:00:00Z`)):'Sin periodo disponible';
const roles={director:'Director Financiero',analyst:'Analista Financiero',admin:'Administrador'};
function App(){
 const [currency,setCurrency]=useState('MXN'),[repair,setRepair]=useState(false),[file,setFile]=useState(null),[preview,setPreview]=useState(null);
 const money=v=>formatMoney(v,currency);
 const [user,setUser]=useState(null),[authReady,setAuthReady]=useState(false),[loginError,setLoginError]=useState(''),[authBusy,setAuthBusy]=useState(false),[users,setUsers]=useState([]);
 const dialog=useRef(null);
 useEffect(()=>{api('/auth/me').then(setUser).catch(()=>setUser(null)).finally(()=>setAuthReady(true));},[]);
 async function signIn(e){e.preventDefault();setLoginError('');setAuthBusy(true);try{const values=Object.fromEntries(new FormData(e.target));const account=await api('/auth/login',{method:'POST',body:JSON.stringify(values)});setUser(account);setDepartment('');setData(null);setAll([]);setPreview(null);setFile(null);setPage('Resumen');setNotice('');dialog.current.close();e.target.reset();setRefresh(v=>v+1);}catch(e){setLoginError(e.message);}finally{setAuthBusy(false);}}
 async function signOut(){setAuthBusy(true);try{await api('/auth/logout',{method:'POST'});setUser(null);setPage('Resumen');setDepartment('');setAll([]);setData(null);setUsers([]);setPreview(null);setFile(null);setNotice('');setRefresh(v=>v+1);}catch(e){setError(e.message);}finally{setAuthBusy(false);}}
 async function createUser(e){
  e.preventDefault();const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));values.username=values.username.trim().toLowerCase();
  setError('');setNotice('');
  if(!/^[a-z0-9._-]{3,100}$/.test(values.username)){setError('Usuario: usa de 3 a 100 letras, números, puntos, guiones o guiones bajos, sin espacios ni acentos.');return;}
  if(values.password.length<12||values.password.length>128){setError('La contraseña debe tener entre 12 y 128 caracteres.');return;}
  setBusy(true);try{await api('/users',{method:'POST',body:JSON.stringify(values)});form.reset();setNotice(`Cuenta ${values.username} creada correctamente.`);try{setUsers(await api('/users'));}catch{setError('La cuenta se creó, pero no se pudo actualizar la lista. Recarga la página.');}}catch(e){setError(e.message);}finally{setBusy(false);}
 }

 useEffect(()=>{if(user?.role==='admin')api('/users').then(setUsers).catch(e=>setError(e.message));else setUsers([]);},[user]);

 const [page,setPage]=useState('Resumen'),[all,setAll]=useState([]),[period,setPeriod]=useState('2026-01'),[department,setDepartment]=useState(''),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(true);
 useEffect(()=>{if(!authReady)return;let active=true;setLoading(true);setError('');Promise.all([api('/financial/entries'),api('/financial/dashboard?'+new URLSearchParams({period,currency,...(department?{category:department}: {})}))]).then(([a,b])=>{if(active){setAll(a);setData(b);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false};},[period,department,refresh,authReady,user,currency]);
 const allowed = user?.role==='director'?['Resumen','Presupuestos','Simulación','Power BI']:user?.role==='analyst'?['Resumen','Presupuestos','Simulación','Importaciones','Power BI']:user?.role==='admin'?['Resumen','Usuarios']:['Resumen'];
 const history=budgetHistory(all,currency,department,period);
 const incomeSelected=Boolean(department)&&all.some(r=>r.currency===currency&&r.category===department&&r.nature==='income')&&!all.some(r=>r.currency===currency&&r.category===department&&r.nature==='expense');
 const depts=[...new Set(all.filter(x=>x.currency===currency).map(x=>x.category))];
 async function inspect(){if(!file)return;setBusy(true);setError('');setPreview(null);try{const f=new FormData();f.append('file',file);f.append('repair_shifted',String(repair));setPreview(await api('/financial/imports/preview',{method:'POST',body:f}));}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function upload(){if(!file||!preview)return;setBusy(true);setError('');setNotice('');try{const f=new FormData();f.append('file',file);f.append('currency',currency);f.append('repair_shifted',String(repair));const res=await api('/financial/imports/csv',{method:'POST',body:f});setNotice(`${res.imported} partidas importadas. ${res.warnings.length} reparaciones confirmadas.`);setPeriod(res.periods.at(-1));setDepartment('');setRefresh(v=>v+1);setFile(null);setPreview(null);}catch(e){setError(e.message);}finally{setBusy(false);}}


 return <div className="shell"><aside><a className="brand" href="#">◈ <span>Presupuesto<small>FINANZAS CORPORATIVAS</small></span></a><div className="navlabel">ESPACIO FINANCIERO</div><nav>{allowed.map((x,i)=><button className={page===x?'active':''} onClick={()=>{setPage(x);setNotice('');}} key={x}><span>{['▦','▤','↗','⇧','◫'][i]}</span>{x}</button>)}</nav><div className="asidefoot"><span className="dot"/> Entorno de desarrollo<small>{user?roles[user.role]:'Vista de demostración'}</small></div></aside><main><header><div>Planeación / <b>{page}</b></div><div className="sessioncontrols">{user?<><span className="badge">{user.username} · {roles[user.role]}</span><button disabled={authBusy} onClick={signOut}>Cerrar sesión</button></>:<button disabled={!authReady} onClick={()=>{setLoginError('');dialog.current.showModal();}}>Iniciar sesión</button>}</div></header><section className="content"><div className="heading"><div><p className="eyebrow">CONTROL PRESUPUESTARIO</p><h1>{page==='Resumen'?'Una visión clara de tus recursos.':page}</h1><p className="subtitle">{descriptions[page]}</p></div><div className="filters"><label>Moneda<select value={currency} onChange={e=>{setCurrency(e.target.value);setDepartment('');setPreview(null);}}>{[...new Set(['MXN','USD','EUR',...all.map(r=>r.currency).filter(Boolean)])].map(c=><option key={c}>{c}</option>)}</select></label><label>Periodo<input type="month" value={period} onChange={e=>setPeriod(e.target.value)} required/></label><label>Categoría<select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">Todos</option>{depts.map(d=><option key={d}>{d}</option>)}</select></label></div></div>{data?.demo&&<div className="notice">Datos de demostración. {user?'El rol administrativo gestiona cuentas; la información financiera real requiere un rol financiero.':'Inicia sesión para acceder a la información real y a las acciones de tu rol.'}</div>}{error&&<div role="alert" className="error">{error}</div>}{notice&&<div role="status" className="notice">{notice}</div>}{loading&&<p role="status">Cargando información…</p>}
 {page==='Resumen'&&data&&!loading&&<>
 <div className="topgrid dashboard-main">
  <article className="panel historypanel"><div className="paneltitle"><h2>Presupuestos mensuales</h2><span>{history.length} periodos</span></div><p className="muted">Ingresos y egresos del mes seleccionado. Cambia el periodo en el filtro superior para consultar otro mes.</p>
   <div className="historylist">{history.length?history.map(month=><section className={'historymonth '+(month.period===period?'selectedmonth':'')} key={month.period}>
    <button className="monthbutton" onClick={()=>setPeriod(month.period)} aria-pressed={month.period===period}>{monthLabel(month.period)}<span>{month.period===period?'Seleccionado':'Ver periodo →'}</span></button>
    {month.categories.map(row=><div className={'budget '+(row.nature==='income'?'income-budget':'')} key={`${row.nature}:${row.category}`}><div><b>{row.category} <small>{row.nature==='income'?'· Ingreso':'· Egreso'}</small></b><strong className={row.nature==='expense'&&row.utilization>100?'danger':''}>{row.pending?'Pendiente':row.utilization===null?'Sin base':row.utilization.toFixed(1)+'%'}</strong></div>
     {row.utilization===null?<div className="pendingbar" aria-label={row.pending?'Resultado pendiente':'Porcentaje sin base'}/>:<progress value={Math.min(row.utilization,100)} max="100" aria-label={`${row.category}, ${monthLabel(month.period)}: ${row.utilization.toFixed(1)}% de ${row.nature==='income'?'cumplimiento':'ejecución'}`}/>}
     <div className="muted"><span>{row.pending?`${money(row.known)} conocidos · ${row.pending} pendientes`:`${money(row.actual)} ${row.nature==='income'?'recibidos':'utilizados'}`}</span><span>de {money(row.budget)}</span></div></div>)}
   </section>):<div className="empty"><h3>Sin partidas para esta selección</h3><p>No hay partidas para el mes, categoría y moneda elegidos. Cambia los filtros o importa un archivo.</p>{user?.role==='analyst'&&<button onClick={()=>setPage('Importaciones')}>Cargar histórico →</button>}</div>}</div>
  </article>
  <article className="forecast"><p className="eyebrow">PREDICCIÓN DEL SIGUIENTE MES</p><h3>{monthLabel(data.prediction.next_period)}</h3><h2>{incomeSelected?'Solo egresos':data.prediction.amount===null?'Sin datos completados':money(data.prediction.amount)}</h2><p>{incomeSelected?'La predicción actual estima egresos. Selecciona una categoría de gastos o «Todos» para consultarla.':'Gasto proyectado de referencia'}</p><div className="forecastnote">{data.prediction.method}<br/>{data.prediction.months} meses usados: {data.prediction.periods_used.map(monthLabel).join(', ')||'ninguno'}<br/>Último periodo del archivo: {monthLabel(data.prediction.reference_period)}</div></article>
 </div>
 <div className="kpis">{[['Ingresos presupuestados',data.income.budget],['Ingresos reales',data.income.actual],['Egresos presupuestados',data.expense.budget],['Egresos reales',data.expense.actual]].map(([k,v])=><article className="panel" key={k}><p>{k}</p><h2>{money(v)}</h2><small>{currency} · {monthLabel(period)}</small></article>)}</div>
 <article className="panel"><div className="paneltitle"><h2>Centro de alertas</h2><span>{monthLabel(period)}</span></div><p className="muted">Resultado del periodo: <b>{money(data.balance)}</b> · {data.income.pending+data.expense.pending} partidas pendientes.</p>{data.alerts.length?data.alerts.map((a,i)=><div className="alert warning" key={i}><b>{a.department}</b><span>{a.message}</span><strong>{money(a.deviation)}</strong></div>):<p className="muted">Sin desviaciones desfavorables en las partidas completadas.</p>}</article>
 </>}

 {page==='Presupuestos'&&<article className="panel"><h2>Partidas del presupuesto</h2><p className="muted">Detalle por concepto. No se asigna un departamento cuando el archivo no lo contiene.</p><div className="tablewrap"><table><thead><tr><th>ID</th><th>Periodo</th><th>Categoría / concepto</th><th>Presupuesto</th><th>Real</th><th>Estado</th></tr></thead><tbody>{all.filter(r=>r.period===period&&r.currency===currency&&(!department||r.category===department)).map(r=><tr key={r.id}><td>{r.source_id}</td><td>{r.period}</td><td>{r.category}<br/><small>{r.concept}</small></td><td>{money(r.budget)}</td><td>{money(r.actual)}</td><td>{r.status==='pendiente'?'Pendiente':'Completado'}</td></tr>)}</tbody></table></div><p className="note">Las partidas se incorporan desde Importaciones con una cuenta de Analista Financiero. Cada registro conserva la categoría, el concepto y el periodo del archivo.</p></article>}
 {page==='Simulación'&&<Simulation key={`${period}:${currency}:${department}:${user?.username}:${refresh}`} entries={all} period={period} currency={currency} category={department} money={money} monthLabel={monthLabel} request={api} loading={loading}/>}
 {page==='Importaciones'&&<article className="panel"><h2>Importar presupuesto por partidas</h2><p className="muted">CSV UTF-8 de hasta 2 MB y 10 000 filas. Confirma la moneda del archivo; los ingresos y egresos se almacenan separados.</p><label>Moneda del archivo<select value={currency} onChange={e=>{setCurrency(e.target.value);setPreview(null);}}>{['MXN','USD','EUR'].map(c=><option key={c}>{c}</option>)}</select></label><label className="filelabel">Selecciona un CSV<input type="file" accept=".csv" disabled={busy} onChange={e=>{setFile(e.target.files[0]||null);setPreview(null);setError('');}}/></label><label className="checklabel"><input type="checkbox" checked={repair} onChange={e=>{setRepair(e.target.checked);setPreview(null);}}/>Confirmo reparar filas cuyo mes esté en Concepto y las cuatro columnas de texto estén desplazadas.</label><button disabled={busy||!file} onClick={inspect}>Validar y previsualizar</button>{preview&&<div className="note"><b>{preview.count} partidas válidas · {preview.pending} pendientes</b>{preview.warnings.map(w=><p key={w}>{w}</p>)}<div className="tablewrap"><table><thead><tr><th>ID</th><th>Periodo</th><th>Categoría</th><th>Concepto</th></tr></thead><tbody>{preview.sample.map(x=><tr key={x.source_id}><td>{x.source_id}</td><td>{x.period}</td><td>{x.category}</td><td>{x.concept}</td></tr>)}</tbody></table></div><button disabled={busy} onClick={upload}>Confirmar importación en {currency}</button></div>}<p className="note">Columnas: ID_Registro, Anio, Mes, Categoria, Subcategoria, Concepto, Presupuesto_Estimado, Gasto_Real, Diferencia_Varianza, Porcentaje_Ejecucion y Estado.<br/>La categoría «Ingresos» se interpreta como ingreso; las demás categorías, como egreso. Confirma que esa regla corresponda a tu archivo.<br/>Pendiente con Gasto_Real=0 se guarda como resultado desconocido. No se aceptan negativos ni ajustes contables en este formato. Se conserva la fila original.</p></article>}

 {page==='Power BI'&&<article className="panel"><span className="badge">Pendiente de configurar</span><h2>Reportes corporativos integrados</h2><p>Primero debemos definir licencias, usuarios y permisos de acceso.</p><p className="muted">Se necesita una aplicación en Microsoft Entra, un workspace y un reporte publicado. El servidor gestionará los secretos y generará tokens después de verificar permisos.</p><p className="note">No se incrustan reportes públicos ni se exponen credenciales en React.</p></article>}
 {page==='Usuarios'&&user?.role==='admin'&&<article className="panel"><h2>Administración de cuentas</h2><form className="form" onSubmit={createUser} noValidate><label>Usuario<input name="username" minLength="3" maxLength="100" autoComplete="off" required/><small>3–100 caracteres; sin espacios ni acentos. Se guarda en minúsculas.</small></label><label>Contraseña inicial<input name="password" type="password" minLength="12" maxLength="128" autoComplete="new-password" required/><small>Entre 12 y 128 caracteres.</small></label><label>Rol<select name="role">{Object.entries(roles).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button disabled={busy}>Crear cuenta</button></form><div className="tablewrap"><table><thead><tr><th>Usuario</th><th>Rol</th><th>Estado</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.username}</td><td>{roles[u.role]}</td><td>{u.active?'Activo':'Inactivo'}</td></tr>)}</tbody></table></div></article>}
 <dialog ref={dialog} className="loginDialog"><div className="paneltitle"><h2>Iniciar sesión</h2><button type="button" aria-label="Cerrar inicio de sesión" onClick={()=>dialog.current.close()}>✕</button></div><p className="muted">Accede con tu cuenta. El rol está asignado por el administrador.</p><form onSubmit={signIn}><label>Usuario<input name="username" autoComplete="username" maxLength="100" autoFocus required/></label><label>Contraseña<input name="password" type="password" autoComplete="current-password" maxLength="128" required/></label>{loginError&&<p role="alert" className="error">{loginError}</p>}<button disabled={authBusy}>{authBusy?'Validando…':'Entrar'}</button></form></dialog>
 <footer>Plataforma de Presupuesto / v0.8 <span>{data?.demo?'Vista de demostración':'Sesión financiera'}</span></footer></section></main></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
