import React, {useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
const money=v=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(v);
async function api(path, options){const r=await fetch('/api'+path,{...options,credentials:'include',headers:{...(!(options?.body instanceof FormData)?{'Content-Type':'application/json'}:{}),'X-Byakuyo':'1',...options?.headers}});const data=await r.json();if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:Array.isArray(data.detail)?data.detail.map(x=>`${({username:'Usuario',password:'Contraseña',role:'Rol'})[x.loc?.at(-1)]||x.loc?.at(-1)||'Campo'}: ${x.msg}`).join('. '):'No se pudo completar la solicitud');return data;}
const descriptions={'Resumen':'Consulta presupuestos, gasto registrado, proyecciones y alertas del periodo.','Presupuestos':'Consulta los presupuestos por departamento y periodo; el director puede registrar nuevos presupuestos.','Simulación':'Ajusta inflación, costos operativos y nómina para comparar escenarios de gasto.','Importaciones':'Carga archivos CSV para incorporar y validar el histórico financiero.','Power BI':'Consulta el estado de la integración de reportes corporativos con Power BI.','Usuarios':'Crea cuentas, asigna roles y consulta los usuarios registrados.'};
const roles={director:'Director Financiero',analyst:'Analista Financiero',admin:'Administrador'};
function App(){
 const [user,setUser]=useState(null),[authReady,setAuthReady]=useState(false),[loginError,setLoginError]=useState(''),[authBusy,setAuthBusy]=useState(false),[users,setUsers]=useState([]);
 const dialog=useRef(null);
 useEffect(()=>{api('/auth/me').then(setUser).catch(()=>setUser(null)).finally(()=>setAuthReady(true));},[]);
 async function signIn(e){e.preventDefault();setLoginError('');setAuthBusy(true);try{const values=Object.fromEntries(new FormData(e.target));const account=await api('/auth/login',{method:'POST',body:JSON.stringify(values)});setUser(account);setDepartment('');setPage('Resumen');setNotice('');dialog.current.close();e.target.reset();setRefresh(v=>v+1);}catch(e){setLoginError(e.message);}finally{setAuthBusy(false);}}
 async function signOut(){setAuthBusy(true);try{await api('/auth/logout',{method:'POST'});setUser(null);setPage('Resumen');setDepartment('');setAll([]);setData(null);setUsers([]);setNotice('');setRefresh(v=>v+1);}catch(e){setError(e.message);}finally{setAuthBusy(false);}}
 async function createUser(e){
  e.preventDefault();const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));values.username=values.username.trim().toLowerCase();
  setError('');setNotice('');
  if(!/^[a-z0-9._-]{3,100}$/.test(values.username)){setError('Usuario: usa de 3 a 100 letras, números, puntos, guiones o guiones bajos, sin espacios ni acentos.');return;}
  if(values.password.length<12||values.password.length>128){setError('La contraseña debe tener entre 12 y 128 caracteres.');return;}
  setBusy(true);try{await api('/users',{method:'POST',body:JSON.stringify(values)});form.reset();setNotice(`Cuenta ${values.username} creada correctamente.`);try{setUsers(await api('/users'));}catch{setError('La cuenta se creó, pero no se pudo actualizar la lista. Recarga la página.');}}catch(e){setError(e.message);}finally{setBusy(false);}
 }

 useEffect(()=>{if(user?.role==='admin')api('/users').then(setUsers).catch(e=>setError(e.message));else setUsers([]);},[user]);

 const [page,setPage]=useState('Resumen'),[all,setAll]=useState([]),[period,setPeriod]=useState('2026-09'),[department,setDepartment]=useState(''),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[scenario,setScenario]=useState({inflation:0,operating:0,payroll:0}),[result,setResult]=useState(null),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(true);
 useEffect(()=>{if(!authReady)return;let active=true;setLoading(true);setError('');setResult(null);Promise.all([api('/budgets'),api('/dashboard?'+new URLSearchParams({period,...(department?{department}: {})}))]).then(([a,b])=>{if(active){setAll(a);setData(b);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false};},[period,department,refresh,authReady,user]);
 const allowed = user?.role==='director'?['Resumen','Presupuestos','Simulación','Power BI']:user?.role==='analyst'?['Resumen','Presupuestos','Simulación','Importaciones','Power BI']:user?.role==='admin'?['Resumen','Usuarios']:['Resumen'];
 const depts=[...new Set(all.map(x=>x.department))];
 async function upload(e){const file=e.target.files[0];if(!file)return;setBusy(true);setError('');setNotice('');try{const f=new FormData();f.append('file',file);const r=await api('/imports/csv',{method:'POST',body:f});setNotice(`${r.imported} registros importados`);setRefresh(v=>v+1);}catch(e){setError(e.message);}finally{setBusy(false);e.target.value='';}}
 async function simulate(){setBusy(true);setError('');try{setResult(await api('/simulations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({period,department:department||null,...scenario})}));}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function create(e){e.preventDefault();setBusy(true);setError('');try{const f=Object.fromEntries(new FormData(e.target));await api('/budgets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});setNotice('Presupuesto registrado');setRefresh(v=>v+1);e.target.reset();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="shell"><aside><a className="brand" href="#">◈ <span>byakuyo<small>FINANZAS CORPORATIVAS</small></span></a><div className="navlabel">ESPACIO FINANCIERO</div><nav>{allowed.map((x,i)=><button className={page===x?'active':''} onClick={()=>{setPage(x);setNotice('');}} key={x}><span>{['▦','▤','↗','⇧','◫'][i]}</span>{x}</button>)}</nav><div className="asidefoot"><span className="dot"/> Entorno de desarrollo<small>{user?roles[user.role]:'Vista de demostración'}</small></div></aside><main><header><div>Planeación / <b>{page}</b></div><div className="sessioncontrols">{user?<><span className="badge">{user.username} · {roles[user.role]}</span><button disabled={authBusy} onClick={signOut}>Cerrar sesión</button></>:<button disabled={!authReady} onClick={()=>{setLoginError('');dialog.current.showModal();}}>Iniciar sesión</button>}</div></header><section className="content"><div className="heading"><div><p className="eyebrow">CONTROL PRESUPUESTARIO</p><h1>{page==='Resumen'?'Una visión clara de tus recursos.':page}</h1><p className="subtitle">{descriptions[page]}</p></div><div className="filters"><label>Periodo<input type="month" value={period} onChange={e=>setPeriod(e.target.value)} required/></label><label>Departamento<select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">Todos los departamentos</option>{depts.map(d=><option key={d}>{d}</option>)}</select></label></div></div>{data?.demo&&<div className="notice">Datos de demostración. {user?'Tu rol administrativo gestiona cuentas; los datos financieros requieren un rol financiero.':'Inicia sesión para acceder a la información real y a las acciones de tu rol.'}</div>}{error&&<div role="alert" className="error">{error}</div>}{notice&&<div role="status" className="notice">{notice}</div>}{loading&&<p role="status">Cargando información…</p>}
 {page==='Resumen'&&data&&!loading&&<><div className="topgrid"><article className="panel"><div className="paneltitle"><h2>Presupuestos del periodo</h2><span>{data.budgets.length} departamentos</span></div>{data.budgets.length?data.budgets.map(b=><div className="budget" key={b.id}><div><b>{b.department}</b><strong className={b.utilization>100?'danger':''}>{b.utilization===null?'Sin base':b.utilization.toFixed(1)+'%'}</strong></div><progress value={Math.min(b.utilization||0,100)} max="100"/><div className="muted"><span>{money(b.spent)} utilizados</span><span>de {money(b.amount)}</span></div></div>):<div className="empty"><h3>Empieza con tu información</h3><p>Importa el CSV de ejemplo o registra un presupuesto.</p><button onClick={()=>setPage('Importaciones')}>Cargar histórico →</button></div>}</article><article className="forecast"><p className="eyebrow">PROYECCIÓN DEL SIGUIENTE MES</p><h2>{data.prediction.amount===null?'Sin datos':money(data.prediction.amount)}</h2><p>Gasto mensual de referencia</p><div className="spark" aria-hidden="true">{[35,50,43,65,61,79,90].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div><small>Ilustración · no representa una serie real</small><div className="forecastnote">{data.prediction.method}<br/>{data.prediction.months} meses disponibles · sin validación predictiva</div></article></div><div className="kpis">{[['Presupuesto total',money(data.kpis.budget)],['Gasto registrado',money(data.kpis.spent)],['Saldo disponible',money(data.kpis.available)],['Utilización',data.kpis.utilization===null?'Sin base':data.kpis.utilization.toFixed(1)+'%']].map(([k,v])=><article className="panel" key={k}><p>{k}</p><h2>{v}</h2><small>Periodo seleccionado</small></article>)}</div><article className="panel"><div className="paneltitle"><h2>Centro de alertas</h2><span>Reglas provisionales</span></div>{data.alerts.length?data.alerts.map(a=><div className={'alert '+a.severity} key={a.department}><b>{a.department}</b><span>{a.message}</span><strong>{money(a.deviation)} de desviación</strong></div>):<p className="muted">Sin alertas para los datos del periodo.</p>}</article></>}
 {page==='Presupuestos'&&<article className="panel"><h2>Registrar presupuesto y gasto agregado</h2><p className="muted">Una fila por departamento y mes. Esta versión no gestiona aprobaciones.</p>{user?.role==='director'&&<form onSubmit={create} className="form"><label>Departamento<input name="department" maxLength="100" required/></label><label>Periodo<input name="period" type="month" required defaultValue={period}/></label>{[['amount','Presupuesto'],['payroll','Gasto de nómina'],['operating','Gasto operativo']].map(([name,label])=><label key={name}>{label}<input name={name} type="number" min="0" step="0.01" required/></label>)}<button disabled={busy}>Guardar presupuesto</button></form>}<div className="tablewrap"><table><thead><tr><th>Departamento</th><th>Periodo</th><th>Presupuesto</th><th>Gasto</th></tr></thead><tbody>{all.map(b=><tr key={b.id}><td>{b.department}</td><td>{b.period}</td><td>{money(b.amount)}</td><td>{money(b.spent)}</td></tr>)}</tbody></table></div></article>}
 {page==='Simulación'&&<div className="topgrid"><article className="panel"><h2>Explora un escenario</h2><p className="muted">Aplica ajustes al gasto del periodo seleccionado.</p>{[['inflation','Inflación',-10,30],['operating','Costos operativos',-50,50],['payroll','Nómina',-30,30]].map(([k,label,min,max])=><label className="slider" key={k}>{label}<strong>{scenario[k]}%</strong><input type="range" min={min} max={max} value={scenario[k]} onChange={e=>{setScenario({...scenario,[k]:Number(e.target.value)});setResult(null);}}/></label>)}<button disabled={busy} onClick={simulate}>Calcular escenario →</button></article><article className="panel"><h2>Comparación del escenario</h2>{result?<><p>Base: <b>{money(result.baseline)}</b></p><h2>{money(result.projected)}</h2><p>Diferencia: {money(result.difference)}</p><p className="muted">{result.formula}</p></>:<p className="muted">Modifica los porcentajes y calcula para ver el resultado.</p>}<p className="note">Supuesto provisional: inflación sobre operación; nómina se ajusta por separado. No equivale a una predicción.</p></article></div>}
 {page==='Importaciones'&&<article className="panel upload"><span className="uploadicon">⇧</span><h2>Incorpora tu histórico financiero</h2><p>CSV en UTF-8 · máximo 2 MB · importación completa o rechazo completo.</p><label className="filelabel">{busy?'Procesando…':'Seleccionar archivo CSV'}<input type="file" accept=".csv" disabled={busy} onChange={upload}/></label><p className="note">Columnas: department, period, amount, payroll, operating.<br/>Periodo YYYY-MM; importes positivos con punto decimal. Sin separadores de miles.<br/>Descarga el proyecto y usa examples/presupuestos.csv para probar.<br/>La carga XLSX se implementará en la siguiente etapa.</p></article>}
 {page==='Power BI'&&<article className="panel"><span className="badge">Pendiente de configurar</span><h2>Reportes corporativos integrados</h2><p>Primero debemos definir licencias, usuarios y permisos de acceso.</p><p className="muted">Se necesita una aplicación en Microsoft Entra, un workspace y un reporte publicado. El servidor gestionará los secretos y generará tokens después de verificar permisos.</p><p className="note">No se incrustan reportes públicos ni se exponen credenciales en React.</p></article>}
 {page==='Usuarios'&&user?.role==='admin'&&<article className="panel"><h2>Administración de cuentas</h2><form className="form" onSubmit={createUser} noValidate><label>Usuario<input name="username" minLength="3" maxLength="100" autoComplete="off" required/><small>3–100 caracteres; sin espacios ni acentos. Se guarda en minúsculas.</small></label><label>Contraseña inicial<input name="password" type="password" minLength="12" maxLength="128" autoComplete="new-password" required/><small>Entre 12 y 128 caracteres.</small></label><label>Rol<select name="role">{Object.entries(roles).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button disabled={busy}>Crear cuenta</button></form><div className="tablewrap"><table><thead><tr><th>Usuario</th><th>Rol</th><th>Estado</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.username}</td><td>{roles[u.role]}</td><td>{u.active?'Activo':'Inactivo'}</td></tr>)}</tbody></table></div></article>}
 <dialog ref={dialog} className="loginDialog"><div className="paneltitle"><h2>Iniciar sesión</h2><button type="button" aria-label="Cerrar inicio de sesión" onClick={()=>dialog.current.close()}>✕</button></div><p className="muted">Accede con tu cuenta. El rol está asignado por el administrador.</p><form onSubmit={signIn}><label>Usuario<input name="username" autoComplete="username" maxLength="100" autoFocus required/></label><label>Contraseña<input name="password" type="password" autoComplete="current-password" maxLength="128" required/></label>{loginError&&<p role="alert" className="error">{loginError}</p>}<button disabled={authBusy}>{authBusy?'Validando…':'Entrar'}</button></form></dialog>
 <footer>Byakuyo / v0.2 <span>{data?.demo?'Vista de demostración':'Sesión financiera'}</span></footer></section></main></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
